name: Creative Peg
favicon: null
layout_spectrum: 0.99929
typography_spectrum: 0.1303929896093905
title: Marketing - Web Design - Branding - Logos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-40196779-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e888e'
    - '#a12643'
    - '#000000'
    - '#00ffff'
    - '#ffffff'
  brandStrength: 0.5544235452543944
  lightness: 0.8222135368268937
  saturation: 0.2990440351422876
  rhythmicContrast: 0.6191178346052766
purpose: []
